import {
  Graph,
  layout as dagreLayout,
  type EdgeLabel,
  type GraphLabel,
  type NodeLabel,
} from "@dagrejs/dagre";
import type {
  AgentNodeConfig,
  AgentStatus,
  AppSettings,
  ChatMessage,
  Edge,
  EdgeId,
  EditBatch,
  FileChangeRecord,
  Node,
  NodeId,
  NodeToolConfig,
  ProviderProfile,
  ReasoningEffortOption,
  SubagentSummary,
  Workflow,
  WorkflowRunState,
  WorkflowSettings,
} from "../types";
import { PROVIDER_ORDER } from "../../constants/providers";

export const NODE_WIDTH = 320;
export const NODE_HEIGHT = 88;
const DAGRE_LAYOUT_ORIGIN_X = 96;
const DAGRE_LAYOUT_ORIGIN_Y = 96;
const DAGRE_LAYOUT_NODE_SEP = 96;
const DAGRE_LAYOUT_RANK_SEP = 112;

/** Backend historically emitted camelCase multi-word statuses over IPC. */
const AGENT_STATUS_ALIASES: Record<string, AgentStatus> = {
  awaitingInput: "awaiting_input",
  awaitingToolApproval: "awaiting_tool_approval",
  runningTool: "running_tool",
};

export function normalizeAgentStatus(status: string): AgentStatus {
  return AGENT_STATUS_ALIASES[status] ?? (status as AgentStatus);
}

export function normalizeRunState(state: WorkflowRunState): WorkflowRunState {
  const statusByNode = Object.fromEntries(
    Object.entries(state.statusByNode).map(([nodeId, status]) => [
      nodeId,
      normalizeAgentStatus(String(status)),
    ]),
  ) as Record<NodeId, AgentStatus>;
  return { ...state, statusByNode };
}

export function providerDisplayOrder(settings: AppSettings): string[] {
  const providerIds = Object.keys(settings.providers);
  const ordered = PROVIDER_ORDER.filter((providerId) => providerId in settings.providers);
  const extras = providerIds
    .filter(
      (providerId) =>
        !PROVIDER_ORDER.includes(providerId as (typeof PROVIDER_ORDER)[number]),
    )
    .sort();
  return [...ordered, ...extras];
}

export function nextNodePlacement(workflow: Workflow): { index: number; x: number; y: number } {
  const index = workflow.nodes.length;
  return {
    index,
    x: 96 + index * 32,
    y: 96 + index * 20,
  };
}

/** Arrange workflow nodes by DAG layer so autogenerated drafts remain readable. */
export function normalizeWorkflowLayout(workflow: Workflow): Workflow {
  const next = cloneWorkflow(workflow);
  const layers = executionLayers(next);
  const nodesById = new Map(next.nodes.map((node) => [node.id, node]));

  const originX = 96;
  const originY = 96;
  const layerGapX = NODE_WIDTH + 96;
  const rowGapY = NODE_HEIGHT + 84;

  for (const [layerIndex, layer] of layers.entries()) {
    const layerTop = originY - ((layer.length - 1) * rowGapY) / 2;
    for (const [rowIndex, nodeId] of layer.entries()) {
      const node = nodesById.get(nodeId);
      if (!node) {
        continue;
      }
      node.position.x = originX + layerIndex * layerGapX;
      node.position.y = layerTop + rowIndex * rowGapY;
    }
  }

  return next;
}

export function dagreLayoutWorkflowLeftToRight(workflow: Workflow): Workflow {
  const next = cloneWorkflow(workflow);
  if (next.nodes.length === 0) {
    return next;
  }

  const graph = new Graph<GraphLabel, NodeLabel, EdgeLabel>()
    .setGraph({
      rankdir: "LR",
      nodesep: DAGRE_LAYOUT_NODE_SEP,
      ranksep: DAGRE_LAYOUT_RANK_SEP,
      marginx: 0,
      marginy: 0,
      ranker: "network-simplex",
    })
    .setDefaultEdgeLabel(() => ({}));
  const nodeIds = new Set(next.nodes.map((node) => node.id));

  for (const node of next.nodes) {
    graph.setNode(node.id, {
      width: NODE_WIDTH,
      height: NODE_HEIGHT,
    });
  }
  for (const edge of next.edges) {
    if (nodeIds.has(edge.from) && nodeIds.has(edge.to)) {
      graph.setEdge(edge.from, edge.to);
    }
  }

  dagreLayout(graph);

  const positions = new Map<NodeId, { x: number; y: number }>();
  for (const node of next.nodes) {
    const laidOut = graph.node(node.id);
    if (typeof laidOut?.x !== "number" || typeof laidOut.y !== "number") {
      continue;
    }
    positions.set(node.id, {
      x: laidOut.x - NODE_WIDTH / 2,
      y: laidOut.y - NODE_HEIGHT / 2,
    });
  }
  if (positions.size === 0) {
    return next;
  }

  const minX = Math.min(...Array.from(positions.values(), (position) => position.x));
  const minY = Math.min(...Array.from(positions.values(), (position) => position.y));
  for (const node of next.nodes) {
    const position = positions.get(node.id);
    if (!position) {
      continue;
    }
    node.position.x = Math.round(position.x - minX + DAGRE_LAYOUT_ORIGIN_X);
    node.position.y = Math.round(position.y - minY + DAGRE_LAYOUT_ORIGIN_Y);
  }

  return next;
}
export function createEmptyToolConfig(): NodeToolConfig {
  return {
    approvalMode: "write",
  };
}
export type WorkflowCanvasGraphNode = {
  id: NodeId;
  label: string;
  position: Node["position"];
};

export type WorkflowCanvasGraphEdge = {
  id: EdgeId;
  from: NodeId;
  to: NodeId;
};

export type WorkflowCanvasGraph = {
  id: Workflow["id"];
  nodes: WorkflowCanvasGraphNode[];
  edges: WorkflowCanvasGraphEdge[];
};

export type WorkflowCanvasStatusByNode = Readonly<Record<NodeId, AgentStatus>>;

export type WorkflowCanvasSubagent = {
  id: string;
  name: string;
  purpose: string;
  status: SubagentSummary["status"];
};

export type WorkflowCanvasSubagentsByNode = Readonly<Record<NodeId, WorkflowCanvasSubagent[]>>;

export function cloneWorkflow(workflow: Workflow): Workflow {
  return {
    id: workflow.id,
    name: workflow.name,
    nodes: workflow.nodes.map(cloneNode),
    edges: workflow.edges.map(cloneEdge),
    settings: {
      shared_context: workflow.settings?.shared_context ?? "",
      schedule: workflow.settings?.schedule ?? null,
      retry_policy: workflow.settings?.retry_policy ?? {
        max_attempts: 3,
        backoff_ms: 1_000,
      },
      provider_id: workflow.settings?.provider_id ?? null,
      reasoning_effort:
        workflow.settings?.reasoning_effort ?? workflow.settings?.reasoningEffort ?? null,
      reasoning_budget_tokens:
        workflow.settings?.reasoning_budget_tokens ??
        workflow.settings?.reasoningBudgetTokens ??
        null,
    },
  };
}

export function cloneSettings(settings: AppSettings): AppSettings {
  return {
    active_provider: settings.active_provider,
    providers: Object.fromEntries(
      Object.entries(settings.providers).map(([providerId, profile]) => [
        providerId,
        cloneProviderProfile(profile),
      ]),
    ),
    skill_search_paths: settings.skill_search_paths
      ? [...settings.skill_search_paths]
      : undefined,
    lsp: settings.lsp ? { ...settings.lsp } : undefined,
    mcp: settings.mcp
      ? {
          servers: settings.mcp.servers.map((server) => ({
            ...server,
            args: [...server.args],
            env: { ...server.env },
          })),
          discoverExternal: settings.mcp.discoverExternal,
          disabledDiscoveredIds: settings.mcp.disabledDiscoveredIds
            ? [...settings.mcp.disabledDiscoveredIds]
            : undefined,
        }
      : undefined,
    local_diagnostics: settings.local_diagnostics
      ? { ...settings.local_diagnostics }
      : undefined,
  };
}

export function activeProfile(settings: AppSettings): ProviderProfile {
  return settings.providers[settings.active_provider] ?? Object.values(settings.providers)[0];
}

export function reasoningEffortOptions(profile: ProviderProfile): ReasoningEffortOption[] {
  return profile.reasoning_effort_options ?? profile.reasoningEffortOptions ?? [];
}

export function defaultReasoningBudgetTokens(
  profile: ProviderProfile,
): Record<string, number> {
  return (
    profile.default_reasoning_budget_tokens ?? profile.defaultReasoningBudgetTokens ?? {}
  );
}

export function defaultReasoningEffort(profile: ProviderProfile): string | null {
  return profile.default_reasoning_effort ?? profile.defaultReasoningEffort ?? null;
}

export function reasoningBudgetForEffort(
  profile: ProviderProfile,
  effort: string,
): number | undefined {
  const option = reasoningEffortOptions(profile).find((entry) => entry.value === effort);
  if (!option?.uses_budget_tokens) {
    return undefined;
  }
  return defaultReasoningBudgetTokens(profile)[effort];
}

export function agentReasoningEffort(agent: AgentNodeConfig): string | null {
  return agent.reasoning_effort ?? agent.reasoningEffort ?? null;
}

export function agentReasoningBudgetTokens(agent: AgentNodeConfig): number | null {
  const budget = agent.reasoning_budget_tokens ?? agent.reasoningBudgetTokens;
  return budget ?? null;
}

export function workflowReasoningEffort(settings: WorkflowSettings): string | null {
  return settings.reasoning_effort ?? settings.reasoningEffort ?? null;
}

export function workflowReasoningBudgetTokens(settings: WorkflowSettings): number | null {
  const budget = settings.reasoning_budget_tokens ?? settings.reasoningBudgetTokens;
  return budget ?? null;
}

export function withDefaultReasoningFromWorkflow(
  agent: AgentNodeConfig,
  settings: WorkflowSettings,
): AgentNodeConfig {
  const effort = workflowReasoningEffort(settings);
  if (!effort || agentReasoningEffort(agent)) {
    return agent;
  }
  const budget = workflowReasoningBudgetTokens(settings);
  return {
    ...agent,
    reasoning_effort: effort,
    reasoning_budget_tokens: budget,
  };
}

export function withDefaultReasoningFromProfile(
  agent: AgentNodeConfig,
  profile: ProviderProfile,
): AgentNodeConfig {
  const effort = defaultReasoningEffort(profile);
  if (!effort || agentReasoningEffort(agent)) {
    return agent;
  }
  const budget = reasoningBudgetForEffort(profile, effort);
  return {
    ...agent,
    reasoning_effort: effort,
    reasoning_budget_tokens: budget ?? null,
  };
}

/** Match persisted backend run state to the workflow whose nodes it describes. */
export function inferRunStateWorkflowId(
  runState: WorkflowRunState | null | undefined,
  workflows: Workflow[],
): string | null {
  if (!runState) {
    return null;
  }
  const nodeIds = new Set([
    ...Object.keys(runState.statusByNode),
    ...Object.keys(runState.chatLogs),
  ]);
  if (nodeIds.size === 0) {
    return null;
  }

  for (const workflow of workflows) {
    const workflowNodeIds = workflow.nodes.map((node) => node.id);
    if (workflowNodeIds.length === 0) {
      continue;
    }
    if (workflowNodeIds.every((id) => nodeIds.has(id))) {
      return workflow.id;
    }
  }
  return null;
}

export function createIdleRunState(workflow: Workflow): WorkflowRunState {
  const statusByNode = workflow.nodes.reduce<Record<NodeId, AgentStatus>>((acc, node) => {
    acc[node.id] = "idle";
    return acc;
  }, {});
  const chatLogs = workflow.nodes.reduce<Record<NodeId, []>>((acc, node) => {
    acc[node.id] = [];
    return acc;
  }, {});
  return {
    active: false,
    awaitingNodeId: null,
    awaitingNodeIds: [],
    activeManualNodeId: null,
    activeToolCallId: null,
    pendingApprovals: [],
    toolCallsByNode: {},
    toolArtifacts: {},
    execApprovalGranted: false,
    statusByNode,
    subagentsByNode: {},
    lastReport: null,
    lastError: null,
    chatLogs,
    runTrace: [],
    outputs: {},
    changedFiles: [],
    changedFilesByNode: {},
    editBatches: [],
  };
}

export function nodeChangedFiles(
  runState: WorkflowRunState | null,
  nodeId: NodeId | null,
): FileChangeRecord[] {
  if (!runState || !nodeId) {
    return [];
  }
  return runState.changedFilesByNode[nodeId] ?? [];
}

export function effectiveChangePath(record: FileChangeRecord): string {
  if (record.op === "rename" && record.renameTo) {
    return record.renameTo;
  }
  return record.path;
}

export function latestChangesByPath(records: FileChangeRecord[]): FileChangeRecord[] {
  const byPath = new Map<string, FileChangeRecord>();
  for (const record of records) {
    if (record.op === "rename") {
      const stale = byPath.get(record.path);
      if (!stale || record.timestampMs >= stale.timestampMs) {
        byPath.delete(record.path);
      }
    }
    const key = effectiveChangePath(record);
    const existing = byPath.get(key);
    if (!existing || record.timestampMs >= existing.timestampMs) {
      byPath.set(key, record);
    }
  }
  return [...byPath.values()];
}

export function runChangedFilePaths(runState: WorkflowRunState | null): string[] {
  if (!runState) return [];
  return latestChangesByPath(runState.changedFiles).map(effectiveChangePath);
}

export function nodeEditBatches(
  runState: WorkflowRunState | null,
  nodeId: NodeId | null,
): EditBatch[] {
  if (!runState || !nodeId) {
    return [];
  }
  return runState.editBatches.filter((batch) => batch.nodeId === nodeId);
}

export function selectedNode(
  workflow: Workflow | undefined,
  selectedNodeId: NodeId | null,
): Node | undefined {
  return workflow?.nodes.find((node) => node.id === selectedNodeId);
}

export function replaceWorkflow(
  workflows: Workflow[],
  nextWorkflow: Workflow,
): Workflow[] {
  const next = workflows.map((workflow) =>
    workflow.id === nextWorkflow.id ? nextWorkflow : workflow,
  );
  return next.some((workflow) => workflow.id === nextWorkflow.id)
    ? next
    : [...next, nextWorkflow];
}

export function removeSelectedNode(
  workflow: Workflow,
  selectedNodeId: NodeId | null,
): Workflow {
  if (!selectedNodeId) {
    return workflow;
  }
  const next = cloneWorkflow(workflow);
  next.nodes = next.nodes.filter((node) => node.id !== selectedNodeId);
  next.edges = next.edges.filter(
    (edge) => edge.from !== selectedNodeId && edge.to !== selectedNodeId,
  );
  return next;
}

export function projectWorkflowCanvasGraph(
  workflow: Workflow | null | undefined,
  previous: WorkflowCanvasGraph | null = null,
): WorkflowCanvasGraph | null {
  if (!workflow) {
    return null;
  }

  if (
    previous &&
    previous.id === workflow.id &&
    sameWorkflowCanvasNodes(previous.nodes, workflow.nodes) &&
    sameWorkflowCanvasEdges(previous.edges, workflow.edges)
  ) {
    return previous;
  }

  return {
    id: workflow.id,
    nodes: workflow.nodes.map((node) => ({
      id: node.id,
      label: node.label,
      position: { x: node.position.x, y: node.position.y },
    })),
    edges: workflow.edges.map((edge) => ({
      id: edge.id,
      from: edge.from,
      to: edge.to,
    })),
  };
}

export function projectWorkflowCanvasStatusByNode(
  runState: WorkflowRunState | null,
  previous: WorkflowCanvasStatusByNode | null = null,
): WorkflowCanvasStatusByNode | null {
  if (!runState) {
    return null;
  }

  if (previous && sameWorkflowCanvasStatusByNode(previous, runState.statusByNode)) {
    return previous;
  }

  return { ...runState.statusByNode };
}

export function projectWorkflowCanvasSubagentsByNode(
  runState: WorkflowRunState | null,
  previous: WorkflowCanvasSubagentsByNode | null = null,
): WorkflowCanvasSubagentsByNode | null {
  if (!runState) {
    return null;
  }

  if (previous && sameWorkflowCanvasSubagentsByNode(previous, runState.subagentsByNode)) {
    return previous;
  }

  const result: Record<NodeId, WorkflowCanvasSubagent[]> = {};
  for (const [nodeId, subs] of Object.entries(runState.subagentsByNode)) {
    result[nodeId] = subs.map((s) => ({
      id: s.id,
      name: s.name,
      purpose: s.purpose,
      status: s.status,
    }));
  }
  return result;
}

export function statusForNode(
  statusByNode: WorkflowCanvasStatusByNode | null,
  nodeId: NodeId,
): AgentStatus {
  const status = statusByNode?.[nodeId];
  return status ? normalizeAgentStatus(status) : "idle";
}

export function nodeOutput(
  runState: WorkflowRunState | null,
  nodeId: NodeId | null,
): unknown | null {
  if (!nodeId) {
    return null;
  }
  return runState?.outputs[nodeId] ?? null;
}

export function isNodeAwaitingInput(
  runState: WorkflowRunState | null,
  nodeId: NodeId | null,
): boolean {
  if (!runState || !nodeId) {
    return false;
  }
  if (runState.awaitingNodeIds?.includes(nodeId)) {
    return true;
  }
  return runState.awaitingNodeId === nodeId;
}

export function pendingApprovalForNode(
  runState: WorkflowRunState | null,
  nodeId: NodeId | null,
) {
  if (!runState?.pendingApprovals || !nodeId) {
    return undefined;
  }
  return runState.pendingApprovals.find((approval) => approval.nodeId === nodeId);
}

export const GLOBAL_RUN_ENTRY_NODE_ID = "__run_entry__" as const;

export function isGlobalRunEntryNodeId(nodeId: NodeId): boolean {
  return nodeId === GLOBAL_RUN_ENTRY_NODE_ID;
}

export function canSendIdleRunKickoff(
  runState: WorkflowRunState | null,
  readinessReady: boolean,
  hasActiveWorkflow: boolean,
  startingRun: boolean,
  text: string,
): boolean {
  return (
    runState?.active !== true &&
    hasActiveWorkflow &&
    !startingRun &&
    readinessReady &&
    text.trim() !== ""
  );
}

/** Root nodes in execution layer 0 (no incoming edges), declaration order preserved. */
export function firstLayerRootNodeIds(workflow: Workflow): NodeId[] {
  const layers = executionLayers(workflow);
  return layers[0] ?? [];
}

export function canSendChat(
  runState: WorkflowRunState | null,
  selectedNodeId: NodeId | null,
  readinessReady: boolean,
  text: string,
): boolean {
  return (
    runState?.active === true &&
    isNodeAwaitingInput(runState, selectedNodeId) &&
    !pendingApprovalForNode(runState, selectedNodeId) &&
    readinessReady &&
    text.trim() !== ""
  );
}

export function isChatComposerBusy(
  runState: WorkflowRunState | null,
  selectedNodeId: NodeId | null,
): boolean {
  if (!runState || !selectedNodeId) {
    return false;
  }

  const status = runState.statusByNode[selectedNodeId];
  return status === "started" || status === "running_tool";
}

const LIVE_AGENT_STATUSES: ReadonlySet<AgentStatus> = new Set([
  "queued",
  "started",
  "running_tool",
  "awaiting_input",
  "awaiting_tool_approval",
]);

export type TranscriptSegment = {
  nodeId: NodeId;
  label: string;
  messages: ChatMessage[];
  status: AgentStatus;
};

export type ChatLayoutProjection = {
  settled: TranscriptSegment[];
  live: TranscriptSegment[];
};

export type ChatNavigationTarget =
  | { mode: "live"; nodeId: NodeId }
  | { mode: "settled"; nodeId: NodeId };

/** Map a canvas node click to live-pick vs settled-filter chat navigation. */
export function chatNavigationForNode(
  layout: ChatLayoutProjection,
  nodeId: NodeId,
): ChatNavigationTarget | null {
  const liveIds = new Set(layout.live.map((segment) => segment.nodeId));
  if (liveIds.has(nodeId)) {
    return { mode: "live", nodeId };
  }
  if (layout.settled.some((segment) => segment.nodeId === nodeId)) {
    return { mode: "settled", nodeId };
  }
  return null;
}

/** Kahn topological layering; preserves workflow.nodes declaration order within each layer. */
export function executionLayers(workflow: Workflow): NodeId[][] {
  const nodeIds = workflow.nodes.map((node) => node.id);
  const nodeSet = new Set(nodeIds);
  const declarationOrder = new Map(nodeIds.map((id, index) => [id, index]));
  const incoming = new Map<NodeId, number>();
  const outgoing = new Map<NodeId, NodeId[]>();

  for (const id of nodeIds) {
    incoming.set(id, 0);
    outgoing.set(id, []);
  }

  for (const edge of workflow.edges) {
    if (!nodeSet.has(edge.from) || !nodeSet.has(edge.to)) {
      continue;
    }
    incoming.set(edge.to, (incoming.get(edge.to) ?? 0) + 1);
    outgoing.get(edge.from)!.push(edge.to);
  }

  const layers: NodeId[][] = [];
  const visited = new Set<NodeId>();
  let ready = nodeIds.filter((id) => incoming.get(id) === 0);

  while (ready.length > 0) {
    layers.push([...ready]);
    for (const id of ready) {
      visited.add(id);
    }

    const nextReady: NodeId[] = [];
    for (const id of ready) {
      for (const child of outgoing.get(id) ?? []) {
        const remaining = (incoming.get(child) ?? 0) - 1;
        incoming.set(child, remaining);
        if (remaining === 0 && !visited.has(child) && !nextReady.includes(child)) {
          nextReady.push(child);
        }
      }
    }

    nextReady.sort(
      (left, right) => (declarationOrder.get(left) ?? 0) - (declarationOrder.get(right) ?? 0),
    );
    ready = nextReady;
  }

  const leftovers = nodeIds.filter((id) => !visited.has(id));
  if (leftovers.length > 0) {
    layers.push(leftovers);
  }

  return layers;
}

function isLiveAgentStatus(runState: WorkflowRunState, status: AgentStatus): boolean {
  return runState.active === true && LIVE_AGENT_STATUSES.has(status);
}

/** True when a transcript segment is an actively running node (not yet folded into history). */
export function isLiveTranscriptSegment(
  runState: WorkflowRunState | null,
  segment: Pick<TranscriptSegment, "status">,
): boolean {
  if (!runState) {
    return false;
  }
  return isLiveAgentStatus(runState, segment.status);
}

/** First time each node appears in the run trace (fallback: DAG traversal). */
export function nodeRunAppearanceOrder(
  runState: WorkflowRunState,
  traversalOrder: NodeId[],
): NodeId[] {
  const ordered: NodeId[] = [];
  const seen = new Set<NodeId>();

  for (const entry of runState.runTrace) {
    if (!seen.has(entry.nodeId)) {
      seen.add(entry.nodeId);
      ordered.push(entry.nodeId);
    }
  }

  for (const nodeId of traversalOrder) {
    if (!seen.has(nodeId) && (runState.chatLogs[nodeId]?.length ?? 0) > 0) {
      seen.add(nodeId);
      ordered.push(nodeId);
    }
  }

  for (const nodeId of Object.keys(runState.chatLogs)) {
    if (!seen.has(nodeId) && (runState.chatLogs[nodeId]?.length ?? 0) > 0) {
      seen.add(nodeId);
      ordered.push(nodeId);
    }
  }

  return ordered;
}

export function sortTranscriptSegmentsByNodeOrder(
  segments: TranscriptSegment[],
  nodeOrder: NodeId[],
): TranscriptSegment[] {
  if (nodeOrder.length === 0) {
    return segments;
  }
  const rank = new Map(nodeOrder.map((nodeId, index) => [nodeId, index]));
  return [...segments].sort((left, right) => {
    const leftRank = rank.get(left.nodeId);
    const rightRank = rank.get(right.nodeId);
    if (leftRank !== undefined && rightRank !== undefined) {
      return leftRank - rightRank;
    }
    if (leftRank !== undefined) {
      return -1;
    }
    if (rightRank !== undefined) {
      return 1;
    }
    return 0;
  });
}

function appendSettledSegment(settled: TranscriptSegment[], segment: TranscriptSegment): void {
  if (settled.some((existing) => existing.nodeId === segment.nodeId)) {
    return;
  }
  settled.push(segment);
}

function effectiveAgentStatus(
  runState: WorkflowRunState,
  nodeId: NodeId,
): AgentStatus {
  const status = statusForNode(runState.statusByNode, nodeId);
  if (!runState.active) {
    return status;
  }
  const awaiting =
    runState.awaitingNodeIds?.includes(nodeId) || runState.awaitingNodeId === nodeId;
  if (awaiting && status === "idle") {
    return "awaiting_input";
  }
  return status;
}

function buildTranscriptSegment(
  nodeId: NodeId,
  label: string,
  messages: ChatMessage[],
  status: AgentStatus,
): TranscriptSegment {
  return { nodeId, label, messages, status };
}

export function projectChatLayout(
  workflow: Workflow | undefined,
  runState: WorkflowRunState | null,
  pickedLiveNodeId?: NodeId | null,
  segmentOrder?: NodeId[] | null,
): ChatLayoutProjection {
  if (!runState) {
    return { settled: [], live: [] };
  }

  const labels = new Map<NodeId, string>();
  const workflowNodeIds = new Set<NodeId>();
  if (workflow) {
    for (const node of workflow.nodes) {
      labels.set(node.id, node.label);
      workflowNodeIds.add(node.id);
    }
  }

  const layers = workflow ? executionLayers(workflow) : [];
  const orderedNodeIds = layers.flat();
  const deletedNodeIds = Object.keys(runState.chatLogs).filter((id) => !workflowNodeIds.has(id));
  const traversalOrder = [...orderedNodeIds, ...deletedNodeIds];
  const appearanceOrder = nodeRunAppearanceOrder(runState, traversalOrder);
  const displayOrder =
    segmentOrder && segmentOrder.length > 0
      ? [
          ...segmentOrder,
          ...appearanceOrder.filter((nodeId) => !segmentOrder.includes(nodeId)),
          ...traversalOrder.filter(
            (nodeId) =>
              !segmentOrder.includes(nodeId) && !appearanceOrder.includes(nodeId),
          ),
        ]
      : [
          ...appearanceOrder,
          ...traversalOrder.filter((nodeId) => !appearanceOrder.includes(nodeId)),
        ];

  const settled: TranscriptSegment[] = [];
  const live: TranscriptSegment[] = [];

  for (const nodeId of traversalOrder) {
    const messages = runState.chatLogs[nodeId] ?? [];
    const status = effectiveAgentStatus(runState, nodeId);
    const label = labels.get(nodeId) ?? nodeId;
    const segment = buildTranscriptSegment(nodeId, label, messages, status);

    if (isLiveAgentStatus(runState, status)) {
      live.push(segment);
      continue;
    }
    if (messages.length > 0) {
      settled.push(segment);
    }
  }

  // One running node streams into the main history. With parallel nodes the chat
  // blocks until the user picks one to talk to; the picked node streams inline and
  // the rest stay in `live` (rendered as a picker) until each completes in turn.
  if (live.length === 1) {
    appendSettledSegment(settled, live[0]);
    live.length = 0;
  } else if (live.length > 1 && pickedLiveNodeId) {
    const pickedIndex = live.findIndex((segment) => segment.nodeId === pickedLiveNodeId);
    if (pickedIndex !== -1) {
      const [picked] = live.splice(pickedIndex, 1);
      appendSettledSegment(settled, picked);
    }
  }

  return {
    settled: sortTranscriptSegmentsByNodeOrder(settled, displayOrder),
    live,
  };
}

function cloneNode(node: Node): Node {
  return {
    id: node.id,
    label: node.label,
    kind: node.kind,
    position: { x: node.position.x, y: node.position.y },
    agent: {
      system_prompt: node.agent.system_prompt,
      task_prompt: node.agent.task_prompt,
      model: node.agent.model,
      output_schema: structuredClone(node.agent.output_schema),
      auto_start: node.agent.auto_start,
      tools: structuredClone(node.agent.tools),
      callable_agents: [...(node.agent.callable_agents ?? [])],
      allow_all_callable_agents: node.agent.allow_all_callable_agents ?? false,
      reasoning_effort: agentReasoningEffort(node.agent),
      reasoning_budget_tokens:
        node.agent.reasoning_budget_tokens ?? node.agent.reasoningBudgetTokens ?? null,
    },
  };
}

function cloneEdge(edge: Edge): Edge {
  return {
    id: edge.id,
    from: edge.from,
    to: edge.to,
  };
}

function cloneProviderProfile(profile: ProviderProfile): ProviderProfile {
  const reasoningOptions = reasoningEffortOptions(profile);
  const budgetTokens = defaultReasoningBudgetTokens(profile);
  return {
    display_name: profile.display_name,
    base_url: profile.base_url,
    transport: profile.transport,
    responses_path: profile.responses_path,
    chat_completions_path: profile.chat_completions_path,
    known_models: [...profile.known_models],
    default_model: profile.default_model,
    editable: profile.editable,
    aws_profile: profile.aws_profile,
    aws_region: profile.aws_region,
    reasoning_effort_options: reasoningOptions.map((option) => ({ ...option })),
    default_reasoning_budget_tokens: { ...budgetTokens },
    default_reasoning_effort: defaultReasoningEffort(profile),
  };
}

function sameWorkflowCanvasNodes(
  previousNodes: WorkflowCanvasGraphNode[],
  nextNodes: Workflow["nodes"],
): boolean {
  if (previousNodes.length !== nextNodes.length) {
    return false;
  }

  for (let index = 0; index < nextNodes.length; index += 1) {
    const previous = previousNodes[index];
    const next = nextNodes[index];
    if (
      previous.id !== next.id ||
      previous.label !== next.label ||
      previous.position.x !== next.position.x ||
      previous.position.y !== next.position.y
    ) {
      return false;
    }
  }

  return true;
}

function sameWorkflowCanvasEdges(
  previousEdges: WorkflowCanvasGraphEdge[],
  nextEdges: Workflow["edges"],
): boolean {
  if (previousEdges.length !== nextEdges.length) {
    return false;
  }

  for (let index = 0; index < nextEdges.length; index += 1) {
    const previous = previousEdges[index];
    const next = nextEdges[index];
    if (
      previous.id !== next.id ||
      previous.from !== next.from ||
      previous.to !== next.to
    ) {
      return false;
    }
  }

  return true;
}

function sameWorkflowCanvasStatusByNode(
  previous: WorkflowCanvasStatusByNode,
  next: Record<NodeId, AgentStatus>,
): boolean {
  const previousKeys = Object.keys(previous);
  const nextKeys = Object.keys(next);

  if (previousKeys.length !== nextKeys.length) {
    return false;
  }

  for (const nodeId of nextKeys) {
    if (previous[nodeId] !== next[nodeId]) {
      return false;
    }
  }

  return true;
}

function sameWorkflowCanvasSubagentsByNode(
  previous: WorkflowCanvasSubagentsByNode,
  next: Record<NodeId, SubagentSummary[]>,
): boolean {
  const previousKeys = Object.keys(previous);
  const nextKeys = Object.keys(next);

  if (previousKeys.length !== nextKeys.length) {
    return false;
  }

  for (const nodeId of nextKeys) {
    const prevSubs = previous[nodeId];
    const nextSubs = next[nodeId];
    if (!prevSubs || prevSubs.length !== nextSubs.length) {
      return false;
    }
    for (let i = 0; i < nextSubs.length; i += 1) {
      if (
        prevSubs[i].id !== nextSubs[i].id ||
        prevSubs[i].name !== nextSubs[i].name ||
        prevSubs[i].status !== nextSubs[i].status
      ) {
        return false;
      }
    }
  }

  return true;
}
