import {
  Graph,
  layout as dagreLayout,
  type EdgeLabel,
  type GraphLabel,
  type NodeLabel,
} from "@dagrejs/dagre";
import type { NodeId, Workflow } from "../types";
import { cloneWorkflow } from "./clone";

export const NODE_WIDTH = 320;
export const NODE_HEIGHT = 88;
const DAGRE_LAYOUT_ORIGIN_X = 96;
const DAGRE_LAYOUT_ORIGIN_Y = 96;
const DAGRE_LAYOUT_NODE_SEP = 96;
const DAGRE_LAYOUT_RANK_SEP = 112;

export function nextNodePlacement(workflow: Workflow): { index: number; x: number; y: number } {
  const index = workflow.nodes.length;
  return {
    index,
    x: 96 + index * 32,
    y: 96 + index * 20,
  };
}

/** Arrange workflow nodes by DAG layer so autogenerated drafts remain readable. */
export function normalizeWorkflowLayout(workflow: Workflow): Workflow {
  const next = cloneWorkflow(workflow);
  const layers = executionLayers(next);
  const nodesById = new Map(next.nodes.map((node) => [node.id, node]));

  const originX = 96;
  const originY = 96;
  const layerGapX = NODE_WIDTH + 96;
  const rowGapY = NODE_HEIGHT + 84;

  for (const [layerIndex, layer] of layers.entries()) {
    const layerTop = originY - ((layer.length - 1) * rowGapY) / 2;
    for (const [rowIndex, nodeId] of layer.entries()) {
      const node = nodesById.get(nodeId);
      if (!node) {
        continue;
      }
      node.position.x = originX + layerIndex * layerGapX;
      node.position.y = layerTop + rowIndex * rowGapY;
    }
  }

  return next;
}

export function dagreLayoutWorkflowLeftToRight(workflow: Workflow): Workflow {
  const next = cloneWorkflow(workflow);
  if (next.nodes.length === 0) {
    return next;
  }

  const graph = new Graph<GraphLabel, NodeLabel, EdgeLabel>()
    .setGraph({
      rankdir: "LR",
      nodesep: DAGRE_LAYOUT_NODE_SEP,
      ranksep: DAGRE_LAYOUT_RANK_SEP,
      marginx: 0,
      marginy: 0,
      ranker: "network-simplex",
    })
    .setDefaultEdgeLabel(() => ({}));
  const nodeIds = new Set(next.nodes.map((node) => node.id));

  for (const node of next.nodes) {
    graph.setNode(node.id, {
      width: NODE_WIDTH,
      height: NODE_HEIGHT,
    });
  }
  for (const edge of next.edges) {
    if (nodeIds.has(edge.from) && nodeIds.has(edge.to)) {
      graph.setEdge(edge.from, edge.to);
    }
  }

  dagreLayout(graph);

  const positions = new Map<NodeId, { x: number; y: number }>();
  for (const node of next.nodes) {
    const laidOut = graph.node(node.id);
    if (typeof laidOut?.x !== "number" || typeof laidOut?.y !== "number") {
      continue;
    }
    positions.set(node.id, {
      x: laidOut.x - NODE_WIDTH / 2,
      y: laidOut.y - NODE_HEIGHT / 2,
    });
  }
  if (positions.size === 0) {
    return next;
  }

  const minX = Math.min(...Array.from(positions.values(), (position) => position.x));
  const minY = Math.min(...Array.from(positions.values(), (position) => position.y));
  for (const node of next.nodes) {
    const position = positions.get(node.id);
    if (!position) {
      continue;
    }
    node.position.x = Math.round(position.x - minX + DAGRE_LAYOUT_ORIGIN_X);
    node.position.y = Math.round(position.y - minY + DAGRE_LAYOUT_ORIGIN_Y);
  }

  return next;
}

/** Root nodes in execution layer 0 (no incoming edges), declaration order preserved. */
export function firstLayerRootNodeIds(workflow: Workflow): NodeId[] {
  const layers = executionLayers(workflow);
  return layers[0] ?? [];
}

/** Kahn topological layering; preserves workflow.nodes declaration order within each layer. */
export function executionLayers(workflow: Workflow): NodeId[][] {
  const nodeIds = workflow.nodes.map((node) => node.id);
  const nodeSet = new Set(nodeIds);
  const declarationOrder = new Map(nodeIds.map((id, index) => [id, index]));
  const incoming = new Map<NodeId, number>();
  const outgoing = new Map<NodeId, NodeId[]>();

  for (const id of nodeIds) {
    incoming.set(id, 0);
    outgoing.set(id, []);
  }

  for (const edge of workflow.edges) {
    if (!nodeSet.has(edge.from) || !nodeSet.has(edge.to)) {
      continue;
    }
    incoming.set(edge.to, (incoming.get(edge.to) ?? 0) + 1);
    outgoing.get(edge.from)!.push(edge.to);
  }

  const layers: NodeId[][] = [];
  const visited = new Set<NodeId>();
  let ready = nodeIds.filter((id) => incoming.get(id) === 0);

  while (ready.length > 0) {
    layers.push([...ready]);
    for (const id of ready) {
      visited.add(id);
    }

    const nextReady: NodeId[] = [];
    for (const id of ready) {
      for (const child of outgoing.get(id) ?? []) {
        const remaining = (incoming.get(child) ?? 0) - 1;
        incoming.set(child, remaining);
        if (remaining === 0 && !visited.has(child) && !nextReady.includes(child)) {
          nextReady.push(child);
        }
      }
    }

    nextReady.sort(
      (left, right) => (declarationOrder.get(left) ?? 0) - (declarationOrder.get(right) ?? 0),
    );
    ready = nextReady;
  }

  const leftovers = nodeIds.filter((id) => !visited.has(id));
  if (leftovers.length > 0) {
    layers.push(leftovers);
  }

  return layers;
}
