//! Auto-generated file detection guard (OMP `auto-generated-guard.ts`).

use std::fs::File;
use std::io::Read;
use std::path::Path;

use regex::Regex;
use std::sync::LazyLock;
use thiserror::Error;

const CHECK_BYTE_COUNT: usize = 1024;
const HEADER_LINE_LIMIT: usize = 40;

const KNOWN_GENERATOR_PATTERN: &str = r"(?:protoc(?:-gen-[\w-]+)?|sqlc|buf|swagger(?:-codegen)?|openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|informer-gen|kysely-codegen|napi-rs)";

static HEADER_MARKERS: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    vec![
        Regex::new(r"(?i)@generated\b").expect("marker"),
        Regex::new(r"(?i)\bcode\s+generated\s+by\s+[a-z0-9_.-]+").expect("marker"),
        Regex::new(r"(?i)\bthis\s+file\s+was\s+automatically\s+generated\b").expect("marker"),
        Regex::new(&format!(r"(?i)\bgenerated\s+by\s+{KNOWN_GENERATOR_PATTERN}\b")).expect("marker"),
    ]
});

static FILENAME_PATTERNS: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    vec![
        Regex::new(r"^zz_generated\.").expect("pattern"),
        Regex::new(r"\.pb\.(go|cc|h|c|js|ts)$").expect("pattern"),
        Regex::new(r"_pb2\.py$").expect("pattern"),
        Regex::new(r"_pb2_grpc\.py$").expect("pattern"),
        Regex::new(r"\.gen\.(go|ts|js|py)$").expect("pattern"),
        Regex::new(r"^generated\.(go|ts|js|py)$").expect("pattern"),
        Regex::new(r"\.swagger\.json$").expect("pattern"),
        Regex::new(r"\.openapi\.json$").expect("pattern"),
        Regex::new(r"\.mock\.(go|ts)$").expect("pattern"),
        Regex::new(r"\.mocks?\.(go|ts|js)$").expect("pattern"),
    ]
});

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CommentStyle {
    Slash,
    Hash,
    Sql,
    Html,
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
#[error("{0}")]
pub struct AutoGeneratedBlocked(pub String);

/// Default on; set `PI_EDIT_BLOCK_AUTO_GENERATED=0` to disable.
#[must_use]
pub fn block_auto_generated_enabled() -> bool {
    #[cfg(test)]
    if let Some(enabled) = block_auto_generated_test_override() {
        return enabled;
    }

    !matches!(
        std::env::var("PI_EDIT_BLOCK_AUTO_GENERATED").as_deref(),
        Ok("0") | Ok("false") | Ok("off")
    )
}

#[cfg(test)]
use std::cell::Cell;

#[cfg(test)]
thread_local! {
    static BLOCK_AUTO_GENERATED_OVERRIDE: Cell<Option<bool>> = const { Cell::new(None) };
}

#[cfg(test)]
fn block_auto_generated_test_override() -> Option<bool> {
    BLOCK_AUTO_GENERATED_OVERRIDE.with(Cell::get)
}

/// Thread-local guard for unit tests (parallel-safe; does not touch process env).
#[cfg(test)]
pub(crate) struct BlockAutoGeneratedGuard {
    previous: Option<bool>,
}

#[cfg(test)]
impl BlockAutoGeneratedGuard {
    pub(crate) fn enabled() -> Self {
        Self::with(true)
    }

    pub(crate) fn disabled() -> Self {
        Self::with(false)
    }

    fn with(enabled: bool) -> Self {
        let previous = BLOCK_AUTO_GENERATED_OVERRIDE.with(|cell| {
            let prev = cell.get();
            cell.set(Some(enabled));
            prev
        });
        Self { previous }
    }
}

#[cfg(test)]
impl Drop for BlockAutoGeneratedGuard {
    fn drop(&mut self) {
        BLOCK_AUTO_GENERATED_OVERRIDE.with(|cell| cell.set(self.previous));
    }
}

/// Reject edits when the file on disk appears auto-generated.
pub fn assert_editable_file(absolute_path: &Path, display_path: &str) -> Result<(), AutoGeneratedBlocked> {
    if !block_auto_generated_enabled() {
        return Ok(());
    }

    if let Some(marker) = detect_from_path(absolute_path, display_path) {
        return Err(build_error(display_path, &marker));
    }
    Ok(())
}

/// Reject edits when content prefix appears auto-generated.
pub fn assert_editable_file_content(
    content: &str,
    display_path: &str,
) -> Result<(), AutoGeneratedBlocked> {
    if !block_auto_generated_enabled() {
        return Ok(());
    }

    let prefix = if content.len() > CHECK_BYTE_COUNT {
        &content[..CHECK_BYTE_COUNT]
    } else {
        content
    };
    if let Some(marker) = detect_auto_generated_marker(prefix, display_path) {
        return Err(build_error(display_path, &marker));
    }
    Ok(())
}

fn detect_from_path(absolute_path: &Path, display_path: &str) -> Option<String> {
    if is_auto_generated_filename(display_path) {
        return Path::new(display_path)
            .file_name()
            .and_then(|name| name.to_str())
            .map(str::to_string);
    }

    if !absolute_path.exists() {
        return None;
    }

    let prefix = peek_file_prefix(absolute_path).ok()?;
    detect_auto_generated_marker(&prefix, display_path)
}

fn peek_file_prefix(path: &Path) -> std::io::Result<String> {
    let mut file = File::open(path)?;
    let mut buffer = vec![0_u8; CHECK_BYTE_COUNT];
    let read = file.read(&mut buffer)?;
    buffer.truncate(read);
    Ok(String::from_utf8_lossy(&buffer).into_owned())
}

fn is_auto_generated_filename(file_path: &str) -> bool {
    let file_name = Path::new(file_path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(file_path);
    FILENAME_PATTERNS
        .iter()
        .any(|pattern| pattern.is_match(file_name))
}

fn detect_auto_generated_marker(content: &str, file_path: &str) -> Option<String> {
    let comment_styles = comment_styles_for_path(file_path);
    let header = extract_leading_header_comment_text(content, &comment_styles);
    if header.is_empty() {
        return None;
    }

    for marker in HEADER_MARKERS.iter() {
        if let Some(found) = marker.find(&header) {
            return Some(found.as_str().to_string());
        }
    }
    None
}

fn comment_styles_for_path(file_path: &str) -> Vec<CommentStyle> {
    let normalized = file_path.to_lowercase();
    let file_name = Path::new(&normalized)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(&normalized);

    match file_name {
        "dockerfile" | "makefile" | "justfile" => {
            return vec![CommentStyle::Hash];
        }
        _ => {}
    }

    let ext = Path::new(file_name)
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("");
    let ext = format!(".{ext}");

    match ext.as_str() {
        ".c" | ".cc" | ".cpp" | ".cs" | ".dart" | ".go" | ".h" | ".hpp" | ".java" | ".js"
        | ".jsx" | ".kt" | ".kts" | ".mjs" | ".cjs" | ".php" | ".rs" | ".scala" | ".swift"
        | ".ts" | ".tsx" => vec![CommentStyle::Slash],
        ".py" | ".rb" | ".sh" | ".bash" | ".zsh" | ".yml" | ".yaml" | ".toml" | ".ini"
        | ".cfg" | ".conf" | ".env" | ".pl" | ".r" => vec![CommentStyle::Hash],
        ".sql" => vec![CommentStyle::Sql],
        ".html" | ".htm" | ".xml" | ".svg" | ".xhtml" => vec![CommentStyle::Html],
        _ => Vec::new(),
    }
}

fn extract_leading_header_comment_text(content: &str, comment_styles: &[CommentStyle]) -> String {
    if comment_styles.is_empty() {
        return String::new();
    }

    let include_slash = comment_styles.contains(&CommentStyle::Slash);
    let include_hash = comment_styles.contains(&CommentStyle::Hash);
    let include_sql = comment_styles.contains(&CommentStyle::Sql);
    let include_html = comment_styles.contains(&CommentStyle::Html);

    let stripped = strip_utf8_bom(content);
    let lines: Vec<&str> = stripped.split('\n').collect();
    let mut header_lines = Vec::new();
    let mut started = false;
    let mut in_slash_block = false;
    let mut in_html_block = false;

    for (line_index, line) in lines.iter().enumerate().take(HEADER_LINE_LIMIT) {
        let trimmed = line.trim();
        if line_index == 0 && trimmed.starts_with("#!") {
            continue;
        }

        if in_slash_block {
            header_lines.push(trimmed.to_string());
            if trimmed.contains("*/") {
                in_slash_block = false;
            }
            continue;
        }

        if in_html_block {
            header_lines.push(trimmed.to_string());
            if trimmed.contains("-->") {
                in_html_block = false;
            }
            continue;
        }

        if trimmed.is_empty() {
            if started {
                header_lines.push(String::new());
            }
            continue;
        }

        if include_slash && trimmed.starts_with("//") {
            started = true;
            header_lines.push(trimmed.to_string());
            continue;
        }

        if include_slash && trimmed.starts_with("/*") {
            started = true;
            header_lines.push(trimmed.to_string());
            if !trimmed.contains("*/") {
                in_slash_block = true;
            }
            continue;
        }

        if include_hash && trimmed.starts_with('#') {
            started = true;
            header_lines.push(trimmed.to_string());
            continue;
        }

        if include_sql && trimmed.starts_with("--") {
            started = true;
            header_lines.push(trimmed.to_string());
            continue;
        }

        if include_html && trimmed.starts_with("<!--") {
            started = true;
            header_lines.push(trimmed.to_string());
            if !trimmed.contains("-->") {
                in_html_block = true;
            }
            continue;
        }

        if started {
            break;
        }
        break;
    }

    header_lines.join("\n")
}

fn strip_utf8_bom(content: &str) -> &str {
    content.strip_prefix('\u{feff}').unwrap_or(content)
}

fn build_error(display_path: &str, detected: &str) -> AutoGeneratedBlocked {
    AutoGeneratedBlocked(format!(
        "Cannot modify auto-generated file: {display_path}\n\n\
         This file appears to be automatically generated (detected marker: \"{detected}\").\n\
         Auto-generated files should not be edited directly. Instead:\n\
         1. Find the source file or generator configuration\n\
         2. Make changes to the source\n\
         3. Regenerate the file"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn with_guard_enabled<F: FnOnce()>(test: F) {
        let _guard = BlockAutoGeneratedGuard::enabled();
        test();
    }

    #[test]
    fn blocks_sqlc_header_in_typescript() {
        with_guard_enabled(|| {
            let content = "// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;\n";
            let err = assert_editable_file_content(content, "queries.ts").unwrap_err();
            assert!(err.0.contains("Cannot modify auto-generated file"));
            assert!(err.0.contains("sqlc"));
        });
    }

    #[test]
    fn blocks_at_generated_marker() {
        with_guard_enabled(|| {
            let content = "// @generated\nexport const x = 1;\n";
            let err = assert_editable_file_content(content, "types.ts").unwrap_err();
            assert!(err.0.contains("@generated"));
        });
    }

    #[test]
    fn blocks_pb_go_filename_without_reading_content() {
        with_guard_enabled(|| {
            let temp = tempfile::tempdir().expect("tempdir");
            let path = temp.path().join("api.pb.go");
            fs::write(&path, "package api\n").expect("write");
            let err = assert_editable_file(&path, "api.pb.go").unwrap_err();
            assert!(err.0.contains("api.pb.go"));
        });
    }

    #[test]
    fn allows_hand_written_rust_file() {
        with_guard_enabled(|| {
            let content = "// Hand-written module guard for edit tools.\nfn main() {}\n";
            assert_editable_file_content(content, "main.rs").expect("editable");
        });
    }

    #[test]
    fn allows_create_when_guard_disabled() {
        let _guard = BlockAutoGeneratedGuard::disabled();
        let content = "// Code generated by sqlc. DO NOT EDIT.\n";
        assert_editable_file_content(content, "generated.ts").expect("disabled");
    }

    #[test]
    fn detects_protoc_marker_in_go_header() {
        with_guard_enabled(|| {
            let content = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n";
            let err = assert_editable_file_content(content, "service.pb.go").unwrap_err();
            assert!(err.0.contains("protoc"));
        });
    }
}
